services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - db 
    env_file:
      - .env.local

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee
      MYSQL_PASSWORD: secret
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - './mysql/etc/my.cnf:/etc/my.cnf'

volumes:
  node_modules:
